import { useNavigate } from "react-router-dom";

const QuickActions = () => {
    const navigate = useNavigate()

    return (
        <div className="mt-10">
            <h2 className="text-2xl font-bold mb-6">Quick Actions</h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="card bg-base-100 shadow-lg cursor-pointer hover:shadow-xl transition" onClick={() => navigate("/resume")}>
                    <div className="card-body">
                        <h3 className="card-title"> Upload Resume </h3>

                        <p className="text-base-content/70">Upload your latest resume for interview preparation.</p>
                    </div>
                </div>

                <div className="card bg-base-100 shadow-lg cursor-pointer hover:shadow-xl transition" onClick={() => navigate("/ats-analysis")}>
                    <div className="card-body">
                        <h3 className="card-title"> ATS Analysis </h3>

                        <p className="text-base-content/70"> Analyze your resume with a job description. </p>
                    </div>
                </div>

                <div className="card bg-base-100 shadow-lg cursor-pointer hover:shadow-xl transition" onClick={() => navigate("/create-interview")} >
                    <div className="card-body">
                        <h3 className="card-title"> AI Interview </h3>

                        <p className="text-base-content/70"> Start a mock interview generated by AI. </p>
                    </div>
                </div>

                <div className="card bg-base-100 shadow-lg cursor-pointer hover:shadow-xl transition" onClick={() => navigate("/history")}>
                    <div className="card-body">
                        <h3 className="card-title"> Interview History </h3>
                        <p className="text-base-content/70"> Review your previous interview attempts.</p>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default QuickActions;